repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: pecan

  # A short description of the repository that will show up on GitHub
  description: The Predictive Ecosystem Analyzer (PEcAn) is an integrated ecological bioinformatics toolbox. 



labels:

  - name: Documentation
    color: a2dcf2

  - name: Dockerfile
    color: 0052CC

  - name: Website
    color: 84b6eb

  - name: Base
    color: 1ED626

  - name: Models
    color: C5DEF5

  - name: Modules
    color: FBCA04

  - name: GitHub Actions
    color: 84b6eb

  - name: Scripts
    color: 3B8924

  - name: Tests
    color: ff8c00
  