name: Docker-Stack-Test

on:
  push:
    branches:
      - master
      - develop
      - Docker-Stack-Testing
      - new-branch-for-docker-testing


    tags:
      - '*'

  pull_request:

  merge_group:

  issue_comment:
    types:
      - created

env:
  R_LIBS_USER: /usr/local/lib/R/site-library
  LC_ALL: en_US.UTF-8
  NCPUS: 2
  PGHOST: postgres
  CI: true

jobs:
 

  # ----------------------------------------------------------------------
  # DOCKER STACK TESTS
  # ----------------------------------------------------------------------
  Stack-Test:
    if: github.event_name != 'issue_comment' || startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        name:
            - sipnet_r136

        include:
          - name: sipnet_r136
            modelID: "1000000014"
            siteID: "676"
            siteName: "Willow Creek (US-WCr)"
            pftName: "temperate.deciduous"
            metData: "AmerifluxLBL"
            startDate: "2004/01/01"
            endDate: "2004/12/31"

    #Add more models below in the above format


      


    services:
      postgres:
        image: mdillon/postgis:9.5
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    container: 
      image: pecan/depends

    steps:
    # checkout source code
    - name: work around https://github.com/actions/checkout/issues/766
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
      with:
        set-safe-directory: false

    - name: Set up Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose
    - name: Build and run containers
      run: |
        docker system prune --all --force
        docker-compose up -d postgres
        docker run --rm --network pecan_pecan pecan/db
        
        docker-compose run  bety user guestuser guestuser "Guest User" guestuser@example.com 4 4

        
        docker-compose run  bety user carya illinois "Carya Demo User" carya@example.com 1 1
        docker run --rm --network pecan_pecan --volume pecan_pecan:/data --env FQDN=docker pecan/data:develop

        cp docker/env.example .env
        echo "COMPOSE_PROJECT_NAME=pecan" >> .env
        echo "PECAN_VERSION=develop" >> .env

        docker-compose up -d 



    - name: Wait for services to start
      run: |
       
        docker-compose ps
        sleep 20 # Adjust the duration as needed
        docker-compose ps
        sleep 20
        docker-compose ps
        sleep 20

      
    
    - name: Display running containers
      run: |
        docker-compose ps
        docker network ls 
        docker network inspect bridge


    # run SIPNET test
    # run SIPNET test
    - name: Run cURL command
      run: |
        curl 'http://172.17.0.1/pecan/04-runpecan.php' -v -L -H "Host: pecan.localhost" -X POST  \
        -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' \
        -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://pecan.localhost' -H 'Connection: keep-alive' -H 'Referer: http://pecan.localhost/pecan/03-inputs.php' \
        -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-User: ?1' \
        --data-raw 'hostname=docker&modelid=1000000014&sitegroupid=-1&lat=&lon=&siteid=756&sitename=Duke+Forest+-+loblolly+pine+%28US-Dk3%29&__utma=106807682.1481268696.1686136092.1686503924.1686550986.7&__utmz=106807682.1686136092.1.1.utmcsr%3D%28direct%29%7Cutmccn%3D%28direct%29%7Cutmcmd%3D%28none%29&pft%5B%5D=temperate.coniferous&start=2004%2F01%2F01&end=2004%2F12%2F31&input_poolinitcond=-1&input_met=99000000005&email=&notes='
        


        
        sleep 200
        curl -v -L -H "Host: pecan.localhost" \
        'http://172.17.0.1/pecan/08-finished.php?workflowid=99000000001&hostname=docker&loglines=100'
        curl -v -L -H "Host: pecan.localhost" \
        'http://172.17.0.1/pecan/dataset.php?workflowid=99000000001&type=file&name=workflow.Rout'
             
          curl -v -L -H "Host: pecan.localhost" \
        'http://172.17.0.1/pecan/dataset.php?dataset.php?workflowid=99000000001&type=file&name=run/99000000001/README'

        curl -v -L -H "Host: pecan.localhost" \
        'http://172.17.0.1/pecan/dataset.php?workflowid=99000000001&type=file&name=run/99000000001/job.sh'




        