name: Docker-Stack-Test

on:
  push:
    branches:
      - master
      - develop
      - Docker-Stack-Testing
      - new-branch-for-docker-testing


    tags:
      - '*'

  pull_request:

  merge_group:

  issue_comment:
    types:
      - created

env:
  R_LIBS_USER: /usr/local/lib/R/site-library
  LC_ALL: en_US.UTF-8
  NCPUS: 2
  PGHOST: postgres
  CI: true

jobs:
 

  # ----------------------------------------------------------------------
  # DOCKER STACK TESTS
  # ----------------------------------------------------------------------
  Stack-Test:
    if: github.event_name != 'issue_comment' || startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        name:
            - sipnet_r136

        include:
          - name: sipnet_r136
            modelID: "1000000014"
            siteID: "676"
            siteName: "Willow Creek (US-WCr)"
            pftName: "temperate.deciduous"
            metData: "AmerifluxLBL"
            startDate: "2004/01/01"
            endDate: "2004/12/31"

    #Add more models below in the above format


      


    services:
      postgres:
        image: mdillon/postgis:9.5
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    container: 
      image: pecan/depends

    steps:
    # checkout source code
    - name: work around https://github.com/actions/checkout/issues/766
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
      with:
        set-safe-directory: false

    # run SIPNET test
    # run SIPNET test
    - name: Run cURL command
      run: |
          chmod +x /tests/Docker-Stack-Test.sh
          /tests/Docker-Stack-Test.sh

          
     