# This workflow is based on github action official label action v4.
# This workflow action is triggered on pull request event(on both fork & inside repo)
# Labels will be applied based on filepath modification in PR.
# This workflow uses a regex based labeling config file(.github/labeler.yml) to take labeling decision.

name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: work around https://github.com/actions/checkout/issues/766
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
      with:
        set-safe-directory: false
    - uses: actions/labeler@v4
      with:
        dot: true